### ISSUE TITLE
'fileupload' variable type doesn't work

### ISSUE THREAD

**Issue by tillathenun** [rainlab/pages-plugin#269] opened 2017-06-21 23:06 UTC
I'm trying to add the following to a layout:

```
{variable name="picture" label="Image" tab="Picture" type="fileupload" mode="image"}{/variable}
{variable name="caption" label="Caption" tab="Picture" type="text"}{/variable}
```

The _fileupload_ field doesn't appear, however. The [documentation](http://octobercms.com/plugin/rainlab-pages) mentions that the Repeater field type is unsupported, but makes no mention of _fileupload_.

Am I doing something wrong, or is this a current limitation?

**Comment by jan-vince** [comment] 2017-06-22 06:40
````fileupload```` is not supported with custom fields. 

You will have to extend Pages plugin with your own plugin.

*Duplicate of #242.*

**Comment by tillathenun** [comment] 2017-06-23 10:23
Thanks for that - sorry I missed the original issue. It might be worth adding this limitation to the Documentation since it seems to suggest everything apart from Repeater works?

**Comment by jan-vince** [comment] 2017-06-23 10:38
You are right - there should be a list of supported types for Custom fields.

*If you have time it would be great if you can send PR.*

**Comment by jan-vince** [comment] 2017-06-23 10:43
Don't forget to close this issue.

**Closed** 2017-06-23 10:45 UTC

**Comment by LukeTowers** [comment] 2017-06-27 20:22
Thanks @jan-vince :)
