### ISSUE TITLE
undefined method RainLab\Pages\Widgets\PageList::getCollapseStatus()

### ISSUE THREAD

**Issue by rubenvanderburgh** [rainlab/pages-plugin#317] opened 2017-12-04 10:33 UTC
[2017-12-04 10:02:55] production.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method RainLab\Pages\Widgets\PageList::getCollapseStatus()' in C:\www\portal\vendor\october\rain\src\Extension\ExtendableTrait.php:388

**Comment by LukeTowers** [comment] 2017-12-04 12:24
Duplicate of #315

**Closed by LukeTowers** 2017-12-04 12:24 UTC
