### ISSUE TITLE
Snippets load wrong content from cache when multi language is enabled

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/pages-plugin#205] opened 2016-10-28 13:33 UTC
After adding multiple snippets to both the locales of the content of the static page:

When loading the page for the first time after editing the static page, that specific language gets cached When switching languages something screws up the parsing of the snippets.  As the snippets get rendered as `figures`. 

<img width="931" alt="screen shot 2016-10-28 at 15 29 24" src="https://cloud.githubusercontent.com/assets/1681727/19808095/5d742254-9d23-11e6-9d9e-491595e3a02c.png">

When programmatically clearing the cache with `cache:clear` the content is correct again for the language that gets loaded the first.

Build: 376 (Edge)
Version: 1.2.10
Server: Local Laravel Valet
Browser: Tested on Safari / Chrome / Firefox but this i browser unspecific.

**Comment by peppetv4** [comment] 2016-11-02 21:57
Experiencing the same thing with a customer site (a not very happy customer) with single snippets as well, if anyone finds a way around this until the issue is resolved please let us know!

**Comment by Verbat** [comment] 2016-11-08 10:08
I already mentioned this behavior here:
https://github.com/rainlab/translate-plugin/issues/165

As a quick fix for the moment I use content blocks as it is stated at the translate plugin.

Like this:
welcome.htm will contain the content in the default language.
welcome.fr.htm will contain the content in French.

Add to layout:
{% content "welcome.htm" %}

Depending on the language it loads either default or secondary language.
Perhaps this helps.

**Comment by CptMeatball** [comment] 2016-11-08 10:12
The specific use case I have is that I have snippets that have context-related properties in them. As far as I know I can't add properties to content files, rendering your solution unusable in my use case. 

But thanks for the reference!

**Comment by manuelbua** [comment] 2016-11-11 14:40
I'm encountering the very same issue, but it looks like a reliable workaround is to use the `array` caching mechanism instead of the file storage one: i'm still testing it out, but it looks a "promising" solution in the meantime, if you still want to use snippets and your site caching needs aren't much higher.

**Comment by manuelbua** [comment] 2016-11-11 14:59
Also, one could add a `null` definition for the Laravel's `NullStore` storage in the `config/cache.php` file such as this:
```php
 'stores' => [
        'null' => [
            'driver' => 'null'
        ],
        ...
```

Now one could use this `null` store as the `default` setting:

```php
    'default' => 'null',
```

**Comment by CptMeatball** [comment] 2016-11-11 15:34
What does this accomplish exactly? I'm not sure I understand.

**Comment by manuelbua** [comment] 2016-11-11 15:59
The idea is to avoid using caching for the parser that would load the correct snippet for the specified language: since it looks like it caches the first language loaded and other languages are then left with the `figures` i suspected that disabling caching would work as a temporary workaround.

I'm still testing both the `array` and the `null` stores and it looks like they both effectively suppress the caching mechanism, although the `array` one should at least persist the data in memory for the page load. I'm not too sure because i'm quite new to Laravel and OctoberCMS, but by looking at the souce code, the `null` store effectively disable everything in regards to caching: if the original problem occurs due to some logical bug, then suppressing the caching should suffice until a proper solution is in place, keep in mind that this could put some more pressure on your server because pages are continuously parsed and the result is not stored, hence the more load.

**Comment by daftspunk** [comment] 2016-11-12 04:47
Fixed by https://github.com/rainlab/translate-plugin/issues/165

Please update to the following:
- RainLab.Pages v1.2.12+
- RainLab.Translate v1.2.7+
- October Build 381+

**Closed by daftspunk** 2016-11-12 04:47 UTC
Labels: duplicate
