### ISSUE TITLE
Call to undefined method 

### ISSUE THREAD

**Issue by JarwisMaster** [rainlab/pages-plugin#318] opened 2017-12-06 13:37 UTC
After reinstall have this error
Call to undefined method RainLab\Pages\Widgets\PageList::getCollapseStatus()

**Comment by LukeTowers** [comment] 2017-12-06 15:06
Duplicate of https://github.com/rainlab/pages-plugin/issues/315

**Closed by LukeTowers** 2017-12-06 15:06 UTC
