### ISSUE TITLE
Menus not displayed caused by october 456

### ISSUE THREAD

**Issue by SebastiaanKloos** [rainlab/pages-plugin#396] opened 2019-06-01 12:48 UTC
Since the update of october 456, the static menu component does not work. Menus are not displayed on pages

**Comment by w20k** [comment] 2019-06-01 20:58
Lastest build 456/1.3.0 PP, theme: `Bonjour By RainLab`
Menus are present. Logs, errors, console?

Screenshots:
<img width="795" alt="Screenshot 2019-06-01 at 23 56 26" src="https://user-images.githubusercontent.com/1053320/58753533-21179f80-84c9-11e9-8f0d-e21341e3215f.png">

**Comment by bennothommo** [comment] 2019-06-02 12:45
@SebastiaanKloos Could you please provide a little more information for us - are the nav items still in the backend? Is it simply the component that is failing? Has the menu been saved to the `cms_theme_contents` table in the database?

**Comment by SebastiaanKloos** [comment] 2019-06-02 13:44
@w20k @bennothommo sorry for not providing any information. There are no errors or logs at all. The menus are stored in the database. You can still edit and view the menus in the backend. 

Turning off the cms.databaseTemplates does not solve the issue. Tried it with another october website. Not touched the cms.databaseTemplates config at all. Still no menus.

I will try it with a brand new install of octobercms and a theme.

I already tried to clear the cache. That did not solve the issue.

**Comment by SebastiaanKloos** [comment] 2019-06-02 14:05
It looks like something is going wrong in the Menu.php class file [function getItemsAttribute](https://github.com/rainlab/pages-plugin/blob/d8534dc08380645b9460818e46ae3c92339c6fb5/classes/Menu.php#L86). A manual dump returns this:

```
array (
  'name' => NULL,
  'items' => 
  array (
  ),
  'fileName' => 'footer-sub-menu-1.yaml',
  'content' => 'name: \'Footer sub menu 1\'
items:
    -
        title: Privacybeleid
        nesting: \'\'
        type: url
        url: /
        code: \'\'
        reference: \'\'
        cmsPage: \'\'
        replace: \'\'
        viewBag:
            isHidden: \'0\'
            cssClass: \'\'
            isExternal: \'0\'
    -
        title: \'Algemene voorwaarden\'
        nesting: \'\'
        type: url
        url: /
        code: \'\'
        reference: \'\'
        cmsPage: \'\'
        replace: \'\'
        viewBag:
            isHidden: \'0\'
            cssClass: \'\'
            isExternal: \'0\'
',
  'mtime' => 1559388637,
  'markup' => NULL,
  'code' => NULL,
)
```

**Comment by SebastiaanKloos** [comment] 2019-06-02 14:40
[Link to code](https://github.com/octobercms/october/blob/1ad43554d4ad937a4264472138827ad799f3be1c/modules/cms/classes/Meta.php#L45) switching the `$this->parseContent()` and `$this->attributes` fixes the issue... @bennothommo @w20k

**Comment by LukeTowers** [comment] 2019-06-03 02:27
@SebastiaanKloos could you make a PR with the details?

**Comment by SebastiaanKloos** [comment] 2019-06-03 07:15
@LukeTowers I created a new PR. Thank you for your time.

**Comment by marcomessa** [comment] 2019-06-03 09:04
Hello, i confirm this is related to new upgrade (core 456 | page 1.3.0). The fix is working, but there is another error. When I try to switch language (using RainLab.Translate), after the update I got this error:

```
Type error: Argument 2 passed to October\Rain\Halcyon\Datasource\FileDatasource::selectOne() must be of the type string, null given, called in /Users/marcomessa/dev/arredocad/vendor/october/rain/src/Halcyon/Builder.php on line 309
```

I discovered this error in production ([here, menu patch is applied, but I can't use english version](https://www.arredocad.com/it))while in my local env before the update it was correctly working

**Comment by bennothommo** [comment] 2019-06-03 09:17
@marcomessa Thanks for letting us know. We strongly recommend not running edge updates in production for exactly this reason - the potential for breaking changes.

**Comment by marcomessa** [comment] 2019-06-03 09:19
That's totally true, I forgot the flag while uploading and didn't noticed until today. I'm trying to find a working fix.

**Comment by w20k** [comment] 2019-06-03 10:00
@marcomessa was going to suggest to downgrade with a composer to the latest stable ;)

**Comment by bennothommo** [comment] 2019-06-07 00:15
Fixed by https://github.com/octobercms/october/pull/4362.

@marcomessa, if you find the cause of the issue, would you be able to raise a separate issue for us? :)

**Closed by bennothommo** 2019-06-07 00:15 UTC
Labels: Status: Completed, Type: Bug
