### ISSUE TITLE
Changing layout for new Subpage causes it to lose its parent category

### ISSUE THREAD

**Issue by duncanClicksco** [rainlab/pages-plugin#150] opened 2016-04-26 08:27 UTC
How to replicate:
1. On pages, click "+ Add subpage" to add a child page below a parent
2. Before saving the new page, click to change the layout 
3. Save page and reload/refresh.

Page has been moved from a subpage into the structure root.

**Comment by voveson** [comment] 2016-05-24 20:01
Is anyone working on a PR for this issue?  We'd like to pitch in if needed.

**Comment by daftspunk** [comment] 2016-06-01 19:30
Duplicate of #99

**Closed by daftspunk** 2016-06-01 19:30 UTC
