### ISSUE TITLE
Editor to allow empty span tags

### ISSUE THREAD

**Issue by claudchan** [rainlab/pages-plugin#178] opened 2016-07-13 04:18 UTC
Hi,
How to allowed empty span tags in the editor. I have icons that used span tags to display the icons.

**Comment by daftspunk** [comment] 2016-07-13 08:44
Check Settings > Editor Settings > Allow empty tags

**Comment by claudchan** [comment] 2016-07-13 15:30
I already add in the allow tags. Is not working.

**Comment by claudchan** [comment] 2016-07-14 00:04
Anyone can confirm this still known issue or it just me?

**Comment by daftspunk** [comment] 2016-07-15 06:28
Provide step by step instructions on what you are doing, this will help determine what the problem is.

**Comment by claudchan** [comment] 2016-07-15 10:20
Hi,
My am using OctoberCMS build is 348, plugin: Static Pages > Pages 1.2.8.

1. Settings > Editor Settings > Markup Tags (Tab) > Allowed empty tags. I have added as below:

`textarea, a, span, i, iframe, object, video, style, script`

2. Go to Pages (Static Pages plugin) > Pages > Edit page 'Welcome' (Page that I created):
3. At Froala Editor tools > Code View </>. I paste my codes, example: 

`<ul class="list-icon">
  <li>
    <span class="circle"><span class="icon-chevron-right"></span></span>
    <span class="text-title">Heading title:</span>
    Lorem ipsum dolor sit.
  </li>
</ul>` 

4. Toggle Code View </>.
5. Now click toggle Code View </> again. My icon has been removed.
6. Results:

`<ul class="list-icon">
  <li><span class="text-title">Heading title:</span> Lorem ipsum dolor sit.</li>
</ul>`

Hope above steps is clear.

**Comment by LukeTowers** [comment] 2017-10-25 18:04
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-25 18:04 UTC
