### ISSUE TITLE
Default RTE doesn't allow DIV tags

### ISSUE THREAD

**Issue by richardwo** [rainlab/pages-plugin#116] opened 2015-11-25 15:53 UTC
To reproduce, in static page editor click html button to view source code, add a div tag e.g. `<div>test</div>`, click html button again to view.
Clicking the html button a third time will show that the div has been converted into a p tag.

Is there any way to configure the editor so that div tags input as code are not converted?

**Comment by gavinworks** [comment] 2015-12-06 14:03
I think this is an intentional setting of the Redactor editor that the pages plugin uses. The default set of tags Redactor uses are ['p', 'blockquote', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5']. You can view more in the Redactor docs here: https://imperavi.com/redactor/docs/settings/formatting/

Allowing users to enter div tags in the editor can often seriously screw up a layout. The editor is designed so users can easily edit pure content without being able to mess anything up.

If you have content that requires a div that needs to get injected into the editor content, like a google map or some other widget, you can easily create a partial to be used as a snippet in the editor. A user can just drop the snippet in to the editor and set any additional settings (that you specify in the partial) and you get total control over what get's added.

Alternatively, you could also add a variable to your layout that your users can just fill in. When pages see's a variable in the layout it'll automatically provide the tab and entry fields for your variable so the users can fill out the details.

Makes life easier for your users and you're assured that your layouts don't get screwed up.

**Comment by richardwo** [comment] 2015-12-06 22:35
Thanks - that makes sense.
Is there any way to make Redactor add a class to any images that are added e.g. img-responsive for use with Bootstrap?

**Comment by FelixINX** [comment] 2015-12-06 22:50
Duplicate of #47 . Please close this issue.

**Closed** 2015-12-07 17:40 UTC
