### ISSUE TITLE
No translation in menu list

### ISSUE THREAD

**Issue by bbrandtlv** [rainlab/pages-plugin#222] opened 2016-12-22 19:10 UTC
Hey
Hope i'm doing something wrong. But I dont see translation for menu.
plugin installed. and i can use it in different plugins but not in menu.
Please advice. 
Thanks

**Comment by caa** [comment] 2016-12-23 01:41
I'm not sure if I understand your situation. Try following this [guide on translating menus](https://github.com/rainlab/pages-plugin/issues/190#issuecomment-264368919).

**Comment by dhanishapa** [comment] 2017-01-13 08:42
I have checked the guide. But after adding the code field, it is not showing up in translate message page. with nav prefix. Do I need to do anything to show it up there? Can you please help.

**Comment by caa** [comment] 2017-01-19 09:03
I'm open to doing a screensharing session to see where you're at or you could take screenshots or do a screencapture video.

**Comment by jlannoy** [comment] 2017-01-20 13:56
Same problem here. Adding a code to a menu item doesn't make it show automatically in the translatable messages. Even by refreshing with cache clean.

**Comment by jan-vince** [comment] 2017-01-20 16:51
I have just tested this and for me, translation phrases are shown in table.

This is, what I am using in HTML of menu:

````{{ ('nav.' ~ item.code)|_ }}````

October build: 393
Pages plugin: 1.2.13
Translate plugin: 1.2.9

**Comment by jlannoy** [comment] 2017-01-20 18:44
Ok, I'll test! I didn't understood (or read?) the need to put this code in the menu html... ;) Thanks.

**Comment by bbrandtlv** [comment] 2017-02-08 01:30
finally found
it's simple: please add to the file:
in the htm of the component:

    {% for item in items if not item.viewBag.isHidden %}
    <li role="presentation" class="{{ item.isActive ? 'active' : '' }} {{ item.isChildActive ? 'child-active' : '' }} {{ item.viewBag.cssClass }}">
        {% if item.url %}
            <a href="{{ item.url }}" {{ item.viewBag.isExternal ? 'target="_blank"' }}>
                {{ item.title|_}}
            </a>
        {% else %}
            <span>{{ item.title }}</span>
        {% endif %}

        {% if item.items %}
            <ul>{% partial __SELF__ ~ "::items" items=item.items %}</ul>
        {% endif %}
    </li>
    {% endfor %}

this line:
 {{ item.title|_}}

and this can be translated at least in the plugin. not enough, but still
@jan-vince  check this one - hopefully this will work for you as well.

hope this will be added in regular way!

**Comment by LukeTowers** [comment] 2017-03-03 03:07
This is a quasi duplicate of #190, any further discussion can be done there.

**Closed by LukeTowers** 2017-03-03 03:07 UTC
