### ISSUE TITLE
properties input wrongly escaped

### ISSUE THREAD

**Issue by JurekRaben** [rainlab/pages-plugin#64] opened 2015-08-12 11:57 UTC
Hi,

if I make a property field type "text" and enter there html-tags like

```
<br />
```

the following problems will occur:
1. if I enter 

```
<br />
```

pages plugin will convert it to 

```
<br ></figure>
```

after saving!
2. if I enter

```
<br>
```

and use the twig raw-filter in fronted output, it will be still written as 

```
<br>
```

in the text... Also the twig filter nl2br doesn't work.
##

**Comment by felixinx** [comment] 2015-08-13 13:52
Yes,

the problem is regarding the HTML editor. I can suggest the following fix, but it's not permanent (must be do at each October update).

Go to the file : `modules/backend/formwidgets/richeditor/assets/vendor/redactor/redactor.js`, change this:

`replaceDivs: true,`
to this
`replaceDivs: false,`

Hope it's help.

**Comment by JurekRaben** [comment] 2015-08-15 13:35
Hey thanks! I will try this soon

**Comment by LukeTowers** [comment] 2017-10-25 17:47
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-25 17:47 UTC
