### ISSUE TITLE
Users can access Pages even without permission

### ISSUE THREAD

**Issue by jan-vince** [rainlab/pages-plugin#181] opened 2016-07-18 06:22 UTC
With permissions set to only allow Content access, users still can access and edit Pages.

Icon for Pages is not present in left menu, but when I click on Pages icon in main (top) menu, I get to the list of Pages and I can edit them.

OctoberCMS build: 349
Static Pages plugin: 1.2.8

**Comment by LukeTowers** [comment] 2016-12-23 09:57
Pinging myself to check this out

**Comment by manuelbua** [comment] 2017-05-04 13:49
+1, i can confirm i'm experiencing the same issue where i need the client to only edit menus and not pages.

**Comment by LukeTowers** [comment] 2017-10-25 18:35
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-25 18:35 UTC
Labels: Priority: Medium, Type: Bug

**Comment by LukeTowers** [comment] 2020-04-02 22:26
Fixed in https://github.com/rainlab/pages-plugin/commit/0ea93942df1bd12cb52e9137d8feee31e9429f5e
