### ISSUE TITLE
Menu translations

### ISSUE THREAD

**Issue by jonnydevv** [rainlab/pages-plugin#240] opened 2017-03-15 11:01 UTC
How can i translate menu?
It doesn't show translation messages, neither has options on menu for multilanguage.

**Comment by LukeTowers** [comment] 2017-03-15 19:27
This is a duplicate of #222, #190, and https://github.com/rainlab/translate-plugin/issues/213. Further discussion can be made in #190. There is a bounty open for the issue here: https://www.bountysource.com/issues/37969749-question-are-the-menu-items-be-translatable

**Closed by LukeTowers** 2017-03-15 19:27 UTC
