### ISSUE TITLE
CSS is transformed to default in editor

### ISSUE THREAD

**Issue by FelixINX** [rainlab/pages-plugin#47] opened 2015-06-16 18:06 UTC
Hi,

This is a bug, that is not pleasent. For example, I want to add a Bootstrap Jumbotron in my home page. I go to the editor, and go to code, add my Jumbotron, but after, I can't save my code just like that, I have to return to the WYSIWYG editor, and it transform my code, and the Jumbotron `<div>` go away. The only way to have my Jumbotron, is to go to `/themes/MYTHEME/content/static-pages/PAGE.htm` and edit it.

I will work on it and make a future pull request.

Thanks
##

**Comment by hybridvision** [comment] 2015-06-19 09:46
I'm not sure if it is a bug or by design - the WYSIWYG editor is set to only allow certain tags currently. If you need complex or fragile HTML in your page, the editor is the best place to have it because it can be easily broken.

Instead, have you considered using a snippet? https://octobercms.com/blog/post/introducing-snippets

**Comment by jayalfredprufrock** [comment] 2015-06-20 19:41
I've been struggling with the same problem and have turned off the replaceDivs redactor setting in richeditor.js. Still looking for a more permanent fix. Snippets are great and would almost solve the problem if only we could nest snippets. As it stands, my snippet collection grows too rapidly and prevents me from creating generalized snippets that can be combined to create more complicated component layouts. For instance I have a snippet that creates column-based markup and allows me to specify a content file for each column. This works great, but what if I need to output a google map or some other component/snippet in one of the columns. I'm forced to create a new snippet that includes both the column markup and the component - definitely not DRY.

**Comment by hybridvision** [comment] 2015-06-28 15:23
Nest-able snippets would be handy indeed but I think that can be a tricky thing to implement in a nice interface. You could have something like [shortcodes] that get processed, à la Wordpress, but that gets ugly quickly and is error-prone.

One nice implementation I've seen recently is this: http://www.elegantthemes.com/gallery/divi/documentation/builder-overview/ - it's Wordpress but the concepts are easily transferrable. It gives access to different layout modules and easily organisable blocks of content. In this case the builder interface creates shortcodes that are then processed as normal by Wordpress. It's a bit convoluted but quite flexible since shortcodes can be overridden.

I think the October CMS interface is really well thought out and with time, I'm hopeful it will mature into a very powerful yet user-friendly system for building complex web apps. I'll be watching with interest and contributing wherever I can.

**Comment by felixinx** [comment] 2015-07-13 14:56
Waiting for a pull-request. @hybridvision Snippets could be great, but we want the easier way.

**Comment by LukeTowers** [comment] 2017-10-25 17:52
No longer an issue since October switched to using Froala? 
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-25 17:52 UTC
