### ISSUE TITLE
Page cache not invalidated when updating Snippet properties

### ISSUE THREAD

**Issue by kay899** [rainlab/pages-plugin#279] opened 2017-08-07 17:19 UTC
As requested by @LukeTowers after Slack chat from yesterday:

When I have a component with a dropdown to let the user select the amount of columns his teasers should be shown in the layout this is working perfectly on my local environment.

On the web servers these configuration values should also be cached by the "parsedPageCacheTTL":
https://github.com/octobercms/october/blob/master/config/cms.php#L152

The first selection gets cached correctly. When I then change the value, the whole section where this is needed in the markup disappears from the website, till the time for caching is over and then the columns lists is shown correctly again.

Luke mentioned the problem could be here somewhere:
https://github.com/rainlab/pages-plugin/blob/master/classes/Snippet.php#L298

Thanks 
kay899

**Comment by danielbruni** [comment] 2017-08-30 11:58
Any temp. solution? Thanks in advance.

**Comment by LukeTowers** [comment] 2017-09-03 02:26
Not at the moment @danielbruni, if you would like to look into what's causing the issue, that would be very helpful! Thanks! :)

**Comment by gtmeteor** [comment] 2017-09-08 15:37
I'm apparently having the same problems. I have no idea what caused it or how to fix it... however this is how it started happening:

- Download opcache and zendloader
- Incorrectly add them as extension=php_opcache.dll; extension=ZendLoader.dll to php.ini
- Restart apache
- Do some work with staticPages, start seeing problems.
- Launch php artisan cache:clear, get complains that libraries are invalid.
- remove them from php.ini, restart Apache
- php artisan cache:clear works fine now
- HOWEVER, the staticPage caching is still borked.

Hope that helps :/

**Comment by datune** [comment] 2017-09-19 10:22
Having experienced the same issues I decided to go deep and trace the problem. After spending 3 hours reviewing the code, at least for my specific case, I think I have found why, on saving a page, the snippets are not updated / displayed.  The problem is in getMapCacheKey($theme) and might be related to the backend user language setting. 

So here is what happens when saving a static page: 

> Index.php->onSave() triggers PagesPlugin::clearCache()
> clearCache() method calls SnippetManager::clearCache($theme)
-> This in turn calls Snippet::clearMapCache($theme)
-> This method calls getMapCacheKey() the value returned is "1506193634snippet-map-de"

However, when loading a static page on the frontend, the method Snippet::extractSnippetsFromMarkupCached(...) also calls getMapCacheKey(), but, for reasons I could not figure out yet, this time the key returns "1506193634snippet-map-en".

This is why, on page save, the cache is not correctly invalidated. Changing the locale value in /config/app.php to "de" (which should not be required at all, since the user backend locale has nothing to do with the frontend locale of the visitor)  resolves all my issues. 


My backend user language is currently set to "de", in /config/app.php the locale value is set to "en".

I'm not sure why Snippet::getMapCacheKey(...)
```php
    /**
     * Returns a cache key for this record.
     */
    protected static function getMapCacheKey($theme)
    {
        return crc32($theme->getPath()).'snippet-map-'.Lang::getLocale();
    }
```
returns two different values. Once when executed onSave, and once when displayin a frontend page. The culprit is the call to Lang::getLocale(), but I'm hoping this might help put you on the right track? Let me know if I can help!

**Comment by datune** [comment] 2017-09-19 12:23
PS: This behaviour can easily be reproduced, assuming your backend language is set to "en", open /config/app.php and change the locale value to something other than "en", go to a static page, add a snippet, save it, edit the snippet, save it again.

**Expected behaviour:** Snippet is updated.

**Actual behaviour:** Snippet is not updated on frontend or is not displayed at all.

**Comment by LukeTowers** [comment] 2017-09-19 15:40
@datune this is fantastic, thank you very much for your detailed dive into this! 

The reason Lang::getLocale() would return two different values would be because the Backend Controller class [sets the application locale](https://github.com/octobercms/october/blob/master/modules/backend/classes/Controller.php#L227) in any backend context to be the user's locale. In the frontend, this is just loaded from the [application config](https://github.com/octobercms/library/blob/develop/src/Translation/TranslationServiceProvider.php#L28). 

However, the wrench in the works for all of this is the RainLab.Translate plugin. If present, it [sets the application locale to the current frontend locale](https://github.com/rainlab/translate-plugin/blob/master/classes/Translator.php#L60) which is why the `getMapCacheKey()` looks at `Lang::getLocale()`, because when the RainLab.Translate plugin is present, the cache should only exist on a per language basis.

The problem then becomes, how can we invalidate the page snippet cache for only the current page language without being influenced by the backend user's locale?

**Comment by datune** [comment] 2017-09-20 07:33
@LukeTowers Unless I am misunderstanding, it seems to me that a possible way to fix this would be to retreive the current locale, override the current locale setting in getMapCacheKey to match the application locale, and once the request is finished set the locale back to the previously retreived locale, so as to not be influenced by the current users choosen backend language.  However, I don't know the Translate Plugin...
```php
    /**
     * Returns a cache key for this record.
     */
    protected static function getMapCacheKey($theme)
    {
        $currentLocale = Lang::getLocale();
        $appLocale = Config::.... // retreive locale from app config
        // if locale is different set the locale to $appLocale
        if ($currentLocale != $appLocale) Lang::setLocale($appLocale); // no idea if this works, it's just pseudo code...
        
         // compute theme key
         $key = crc32($theme->getPath()).'snippet-map-'.Lang::getLocale();

         // set locale back to original value
         Lang::setLocale($currentLocale);
         return $key;
    }
```

I don't think this would affect anything else, but I don't know October well enough (yet) to evaluate this properly.

**Comment by LukeTowers** [comment] 2017-09-20 19:17
The problem is that we need to support the correct cache keys for both situations:
1. The RainLab.Translate plugin is installed.
2. The RainLab.Translate plugin is not installed.

I think a better solution might be to provide an event for generating the cache key that the RainLab.Translate plugin can then listen to in order to modify it appropriately only when that plugin is installed. Thoughts?

**Comment by datune** [comment] 2017-09-21 09:55
@LukeTowers 

As far as I can tell, this issue is not related to the Translate Plugin in any way. The page cache is not correctly invalidated, whether or not the Translate Plugin is installed. 

**Without the translate plugin installed:**
- The getMapCacheKey method should not call Lang::getLang(), because (for whatever reason) the backend user language setting directly affects the language returned by Lang::getLang(). 
- getMapCacheKey should simply return the locale as defined in the config file, since this is the default language key used to display (static) pages in the frontend.

The easiest way I found to ensure that we retreive the original value is to simply grab it directly from the config file. All other methods are influenced by the backend user language setting.

**With the translate plugin installed**
Adding an event, as you suggested, is a possible solution, albeit a tricky one, but this is perhaps best discussed at another time.

So, the Rainlab.Translate plugin can simply listen to the event, and alter the current locale as required. 

Here is one way of making all this happen (without the Rainlab.Translate plugin). 

File: Snippet.php
```php
...
use Event;
...
    /**
     * Returns a cache key for this record.
     */
    protected static function getMapCacheKey($theme)
    {
        // Retreive current locale value
        $currentLocale = Lang::getLocale();

        // Grab original application configuration
        $config = Cache::get('rainlab.pages.appConfigArray', function() {
            return require(config_path() . '/app.php');
        });

        // Set the locale to the value found in the configuration
        Lang::setLocale($config['locale']);

        // Allow for changes before creating the key
        Event::fire('rainlab.pages.beforeCreatingCacheKey');

        // Create the cache key
        $key = crc32($theme->getPath()).'snippet-map-'.Lang::getLocale();

        // Set the locale value back to the value before processing
        Lang::setLocale($currentLocale);

        return $key;
    }
```
Now the maintainers of the Rainlab.Plugin can listen to this event and act accordingly:
File: translate\Plugin.php
```php
// I'm guessing in the Plugin's boot method, but like I said, I have no knowledge about the Translate plugin
...
        Event::listen('rainlab.pages.beforeCreatingCacheKey', function() {
            // do your thing
        });
...
```
First and foremost, this resolves the issue of the Pages plugin being affected by the user backend language setting. It also provides an event for other plugins to listen to, in case they need to modify the current locale before the cache key is created. 

Thoughts?

**Comment by LukeTowers** [comment] 2017-09-21 15:48
I'm thinking something much simpler. The whole reason the `Lang::getLocale()` is even included here is specifically because of the RainLab.Translate plugin. As such, we don't need it by default. My solution goes something like this:

```php

**Comment by datune** [comment] 2017-09-21 18:37
Wow! I wasn't aware that the authors of the pages plugin thought it to be a good idea to create coupling where it is not needed. I thought the Pages Plugin needed this, obviously you're approach is way simpler.

I kinda wish I would have known from the get go that Lang::getLocale was only added for another plugin...

**Comment by LukeTowers** [comment] 2017-09-21 19:20
It was only added last year as a fix for a Translate plugin issue: https://github.com/rainlab/pages-plugin/commit/1ef27deb7617a643b0c3c668b3be3fe4340340d5#diff-9026ffe964a5075d8eb97cb071276969

**Comment by LukeTowers** [comment] 2017-09-21 19:46
Should be fixed now by https://github.com/rainlab/translate-plugin/commit/f5ddabbcf907af47a7129157c847472122c4ba7a and https://github.com/rainlab/pages-plugin/commit/204157cd699cd6f0772427952e7be4688050a92b. @kay899 @datune @gtmeteor @danielbruni do you guys mind testing this solution?

**Comment by acasar** [comment] 2017-09-21 21:29
@LukeTowers Event facade is not imported and causes an error. Seems like there is already a PR to fix it: https://github.com/rainlab/pages-plugin/pull/294

**Comment by LukeTowers** [comment] 2017-09-21 22:23
@acasar Merged it, thanks!

**Comment by datune** [comment] 2017-10-04 12:21
@LukeTowers Thanks for your help and work, seems to resolve the issue!

**Comment by LukeTowers** [comment] 2017-10-04 15:31
@datune Happy to get this resolved! Thanks to you as well for your work in identifying the issue!

**Closed by LukeTowers** 2017-10-04 15:31 UTC
Labels: Priority: High, Status: In Progress, Type: Bug

**Comment by szympajka** [comment] 2018-02-02 12:14
Cool!

Thank you that this issue is solved. My October has got the same problem but this solution seems to help!
