### ISSUE TITLE
Repeaters show extended form fields backend

### ISSUE THREAD

**Issue by toughdeveloper** [rainlab/pages-plugin#203] opened 2016-10-24 15:09 UTC
Hi, first of all thanks very much for the plugin and continued work of October, I just have a minor issue when extending the static page plugin. 

I have the following code within the `boot()` method of my Plugin.

``` php
if(PluginManager::instance()->hasPlugin('RainLab.Pages') && $widget->model instanceof \RainLab\Pages\Classes\Page)
{
    $widget->addFields([
        'viewBag[hide_from_search_engines]' => [
            'label'         => 'Hide from search engines',
            'type'          => 'checkbox',
            'comment'       => 'Check this box to prevent the page being indexed by search engines.',
            'tab'           => 'cms::lang.editor.settings'
        ]
    ]);
}
```

This correctly adds the checkbox onto the settings tab, however it also adds the checkbox to each of my repeaters.

My repeater code is as follows:

```
{repeater name="content_sections" label="Hero Images" tab="Section One" prompt="Add another image"}
    <div class="item {% if loop.first %}active{% endif %}" style="background: url({mediafinder name="section_one_background" label="Background"}{/mediafinder}) center center no-repeat;background-size:cover;"></div>
{/repeater}
```

Screenshot of issue described:
![issue](http://i.imgur.com/yGVyEBg.jpg)

Am I doing something wrong here? Thanks.

**Comment by daftspunk** [comment] 2016-10-31 21:25
This is more than likely caused by https://github.com/octobercms/october/issues/2257.

The repeater uses a form widget itself, so when extending the form widget you also extend the repeater.

**Comment by LukeTowers** [comment] 2016-12-23 09:54
@toughdeveloper, @daftspunk, has this been fixed by the resolution to octobercms/october#2257?

**Comment by borisbrue** [comment] 2017-06-14 14:22
Is someone still working on this issue? 
I ran into the same problem with the extended fields.... 
If nobody is working on this right now I will search for a solution this weekend-

**Comment by LukeTowers** [comment] 2017-06-15 00:49
@borisbrue I don't believe anybody is actively working on this issue, so if you want to that would be great! Thanks!

**Comment by daftspunk** [comment] 2017-06-15 02:31
Should've been fixed by https://github.com/octobercms/october/issues/2257

If not, reopen another issue.

**Closed by daftspunk** 2017-06-15 02:31 UTC
Labels: Priority: High, Status: Completed, Type: Bug
